#!/bin/bash
set -e

# Get this file path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

rc=0
brew bundle cleanup --file="$DIR/Brewfile" || rc=$?
# If exit code is 1 ask user if they want to force cleanup
if [ "$rc" -eq 1 ]; then
    read -p "Do you want to force cleanup? (y/n) " -n 1 -r

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        brew bundle cleanup --force --file="$DIR/Brewfile"
    fi
fi
