#!/bin/bash

# Get this file path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Bundle Brewfile
brew bundle dump --describe -f --file=$DIR/Brewfile

# Edit Brewfile and add ", greedy: true" to the end of each line strating with cask
sed -i '' '/^cask/ s/$/, greedy: true/' $DIR/Brewfile

# Chezmoi merge
chezmoi merge-all
