#!/bin/bash
set -e

# Get this file path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if ! command -v brew &>/dev/null; then
  echo "Install brew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "Update brew"
  brew update
fi

# Install brew packages
echo "Install brew packages"
brew bundle -v --file="$DIR/Brewfile"

# Chezmoi
mkdir -p "$HOME/.config/chezmoi"
cp "$DIR/chezmoi.yaml" "$HOME/.config/chezmoi/chezmoi.yaml"
echo "Apply chezmoi"
chezmoi apply --force

# Install oh-my-zsh
echo "Install Oh My ZSH"
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Install Oh My ZSH"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Update macOS
echo "Update macOS"
sudo softwareupdate -i -a --verbose

# Sudo with touchId
echo "Sudo with touchId"
if ! grep -q pam_tid.so /etc/pam.d/sudo; then
  echo "Add pam_tid.so to /etc/pam.d/sudo"
  sudo sed -i '' '2i\
  auth       sufficient     pam_tid.so\
  ' /etc/pam.d/sudo
fi
