#!/bin/bash

# Get this file path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if ! command -v brew &>/dev/null; then
  echo "Install brew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "Update brew"
  brew update
fi

brew bundle -v --no-lock --file=$DIR/Brewfile

# Stowing dotfiles
echo "Stowing dotfiles"
rm -rf ~/.gitconfig ~/.gitignore ~/.zshrc ~/.config/{bat,k9s,nvim,starship.toml}
stow -d $DIR/dotfiles -t $HOME home
stow -d $DIR/dotfiles -t $HOME/.config config

# Install oh-my-zsh
echo "Install Oh My ZSH"
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Install Oh My ZSH"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

sudo softwareupdate -i -a --verbose

# Sudo with touchId:w
if ! grep -q pam_tid.so /etc/pam.d/sudo; then
  echo "Add pam_tid.so to /etc/pam.d/sudo"
  sudo sed -i '' '2i\
  auth       sufficient     pam_tid.so\
  ' /etc/pam.d/sudo
fi
