views:
  v1/namespaces:
    columns:
      - NAME
      - OWNER:.metadata.labels.app\.airnity\.io\/owner
      - STATUS
      - AGE
  v1/nodes:
    columns:
      - NAME
      - STATUS
      - INSTANCE:.metadata.labels.beta\.kubernetes\.io\/instance-type
      - ZONE:.metadata.labels.failure-domain\.beta\.kubernetes\.io\/zone
      - TAINTS
      - VERSION
      - PODS
      - CPU
      - MEM
      - "%CPU"
      - "%MEM"
      - "CPU/A"
      - "MEM/A"
      - AGE
      - ROLE|W
      - GPU|W
