# Inserts a blank line between shell prompts
add_newline = false
continuation_prompt = "▶▶"

# Left prompt
format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$jobs\
$battery\
$os\
$container\
$shell\
$character"""

# Right prompt
right_format = """
$cmd_duration\
$status\
$git_state\
$git_status\
$git_branch\
$git_commit\
$git_metrics\
$kubernetes\
"""


# Left config
[directory]
truncation_symbol = "…/"
truncate_to_repo = true
style= "#2aa198"
read_only = " "

[character]
success_symbol = "[❯](bold #6c71c4)[❯](bold #268bd2)[❯](bold #2aa198)"
error_symbol = "[❯❯❯](bold red)"


# Right config

[status]
disabled = false
format = "[$symbol $status]($style #dc322f) "

[kubernetes]
format = '[$symbol$context(\($namespace\))]($style) '
style = "#2aa198"
disabled = false

[git_branch]
format = "[$symbol$branch]($style) "
style = "#cb4b16"
symbol = " "

[git_status]
format = '([(\[$all_status\]) $ahead_behind]($style) )'
style = 'bold #268bd2'
conflicted = '[=](bold #dc322f)'
ahead = '[$count⇡](bold #d33682)'
behind = '[$count⇣](bold #d33682)'
diverged = '[${ahead_count}⇡${behind_count}⇣](bold #d33682)'
up_to_date = '[✓](bold #859900)'
untracked = '[$count?](bold #cb4b16)'
stashed = '[$count≡](bold #2aa198)'
modified = '[$count!](bold #6c71c4)'
staged = '[$count+](bold #859900)'
renamed = '[$count»](bold white)'
deleted = '[$count✘](bold #dc322f)'

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = " "

[time]
disabled = false
format = '[$time]($style #268bd2) '
time_format = "%T"

[gcloud]
disabled = true
